[package]
name = "zippo"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6.6"
anyhow = "1.0.75"
inquire = "0.6.2"

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
